
--To be updated from the refactoring of the mock data base
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Amber', 4, 'pyro', 'bow', 'mondstadt', 'forsaken_rift', 'freedom', 1);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Kaeya', 4, 'cryo', 'sword', 'mondstadt', 'forsaken_rift', 'ballad', 3);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Lisa', 4, 'electro', 'catalyst', 'mondstadt', 'forsaken_rift', 'ballad', 3);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Barbara', 4, 'hydro', 'catalyst', 'mondstadt', 'forsaken_rift', 'freedom', 1);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Razor', 4, 'electro', 'claymore', 'mondstadt', 'forsaken_rift', 'resistance', 2);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Xiangling', 4, 'pyro', 'polearm', 'liyue', 'taishan_mansion', 'diligence', 2);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Beidou', 4, 'electro', 'claymore', 'liyue', 'taishan_mansion', 'gold', 3);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Xingqiu', 4, 'hydro', 'sword', 'liyue', 'taishan_mansion', 'gold', 3);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Ningguang', 4, 'geo', 'catalyst', 'liyue', 'taishan_mansion', 'prosperity', 1);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Fischl', 4, 'electro', 'bow', 'mondstadt', 'forsaken_rift', 'ballad', 3);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Bennett', 4, 'pyro', 'sword', 'mondstadt', 'forsaken_rift', 'resistance', 2);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Noelle', 4, 'geo', 'claymore', 'mondstadt', 'forsaken_rift', 'resistance', 2);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Chongyun', 4, 'cryo', 'claymore', 'liyue', 'taishan_mansion', 'diligence', 2);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Sucrose', 4, 'anemo', 'catalyst', 'mondstadt','forsaken_rift', 'freedom', 1);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Jean', 5, 'anemo', 'sword', 'mondstadt','forsaken_rift', 'resistance', 2);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Diluc', 5, 'pyro', 'claymore', 'mondstadt','forsaken_rift', 'resistance', 2);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Qiqi', 5, 'cryo', 'sword', 'liyue', 'taishan_mansion', 'prosperity', 1);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Mona', 5, 'hydro', 'catalyst', 'mondstadt', 'forsaken_rift', 'resistance', 2);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Keqing', 5, 'electro', 'sword', 'liyue', 'taishan_mansion', 'prosperity', 1);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Venti', 5, 'anemo', 'bow', 'mondstadt', 'forsaken_rift', 'ballad', 3);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Klee', 5, 'pyro', 'catalyst', 'mondstadt', 'forsaken_rift', 'freedom', 1);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Diona', 4, 'cryo', 'bow', 'mondstadt', 'forsaken_rift', 'freedom', 1);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Tartaglia', 5, 'hydro', 'bow', 'liyue', 'forsaken_rift', 'freedom', 1);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Xinyan', 4, 'pyro', 'claymore', 'liyue', 'taishan_mansion', 'gold', 3);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Zhongli', 5, 'geo', 'polearm', 'liyue', 'taishan_mansion', 'gold', 3);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Albedo', 5, 'geo', 'sword', 'mondstadt', 'forsaken_rift', 'ballad', 3);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Ganyu', 5, 'cryo', 'bow', 'liyue', 'taishan_mansion', 'diligence', 2);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Xiao', 5, 'anemo', 'polearm', 'liyue', 'taishan_mansion', 'prosperity', 1);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Hu_Tao', 5, 'pyro', 'polearm', 'liyue', 'taishan_mansion', 'diligence', 2);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Rosaria', 4, 'cryo', 'polearm', 'mondstadt', 'forsaken_rift', 'ballad', 3);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Yanfei', 4, 'pyro', 'catalyst', 'liyue', 'taishan_mansion', 'gold', 3);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Eula', 5, 'cryo', 'claymore', 'mondstadt', 'forsaken_rift', 'resistance', 2);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Kaedahara_Kazuha', 5, 'anemo', 'sword', 'liyue', 'taishan_mansion', 'diligence', 2);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Kamisato_Ayaka', 5, 'cryo', 'sword', 'inazuma', 'violet_court', 'elegance', 2);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Sayu', 4, 'anemo', 'claymore', 'inazuma', 'violet_court', 'light', 3);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Yoimiya', 5, 'pyro', 'bow', 'inazuma', 'violet_court', 'transience', 1);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Aloy', 5, 'cryo', 'bow', 'mondstadt', 'forsaken_rift', 'freedom', 1);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Kujou_Sara', 4, 'electro', 'bow', 'inazuma', 'violet_court', 'elegance', 2);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Raiden_Shogun', 5, 'electro', 'polearm', 'inazuma', 'violet_court', 'light', 3);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Sangonomiya_Kokomi', 5, 'hydro', 'catalyst', 'inazuma', 'violet_court', 'transience', 1);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Thoma', 4, 'pyro', 'polearm', 'inazuma', 'violet_court', 'transience', 1);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Gorou', 4, 'geo', 'bow', 'inazuma', 'violet_court', 'light', 3);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Arataki_Itto', 5, 'geo', 'claymore', 'inazuma', 'violet_court', 'elegance', 2);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Yunjin', 4, 'geo', 'polearm', 'liyue', 'taishan_mansion', 'diligence', 2);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Shenhe', 5, 'cryo', 'polearm', 'liyue', 'taishan_mansion', 'prosperity', 1);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Yae_Miko', 5, 'electro', 'catalyst', 'inazuma', 'violet_court', 'transience', 1);
INSERT INTO characters (name, star, element, weapon, region, domainname, ascensionMat, ascensiondayid) VALUES ('Kamisato_Ayato', 5, 'hydro', 'sword', 'inazuma', 'violet_court', 'elegance', 2);
