//USED for Adding Data/ Backup Data or reference
//load("Documents/MiniProjects/MongoDBTestAPI/insertManyWeapons.js");

db.Weapons.insertMany([
    {name:"Dark Iron Sword",              star:4, stat:"Elemental Mastery",     type:"Sword", domain:"Hidden Palace of Lianshan Formula",     material:"Guyun",     availability:["Sunday","Monday","Thursday"],        imgurl:"../../assets/data/images/weapons/BlackIronSword.png" },
    {name:"Cool Steel", },
    {name:"Harbinger of Dawn", },
    {name:"Traveler's HAndy Sword", },
    {name:"Fillet Blade", },
    {name:"Skyrider Sword", },
    {name:"Ferrous Shadow", },
    {name:"Bloodstained Greatsword", },
    {name:"White Iron Greatsword", },
    {name:"Debate Club", },
    {name:"Skyrider Greatsword", },
    {name:"White Tassel", },
    {name:"Halberd", },
    {name:"Black Tassel", },
    {name:"Amber Bead", },
    {name:"Magic Guide", },
    {name:"Thrilling Tales of Dragon Slayers", },
    {name:"Otherwordly Story", },
    {name:"Emerald Orb", },
    {name:"Twin Nepherite", },
    {name:"Ebony Bow", },
    {name:"Raven Bow", },
    {name:"Sharpshooter's Oath", },
    {name:"Recurve Bow", },
    {name:"Slingshot", },
    {name:"Messenger", },
    {name:"Favonius Sword", },
    {name:"The Flute", },
    {name:"Sacrificial Sword", },
    {name:"Royal Longsword", },
    {name:"Lion's Roar", },
    {name:"Prototype Rancour", },
    {name:"Iron Sting", },
    {name:"Blackcliff Longsword", },
    {name:"Sword of Descension", },
    {name:"Festering Desire", },
    {name:"The Alley Flash", },
    {name:"Amenoma Kageuchi", },
    {name:"Cinnabar Spindle", },
    {name:"Favonius Greatsword", },
    {name:"The Bell", },
    {name:"Sacrificial Greatsword", },
    {name:"Royal Greatsword", },
    {name:"Rainslasher", },
    {name:"Prototype Archaic", },
    {name:"Whiteblind", },
    {name:"Blackcliff Slasher", },
    {name:"Serpent Spine", },
    {name:"Snow-Tombed Starsilver", },
    {name:"Lithic Blade", },
    {name:"Katsuragikiri Nagamasa", },
    {name:"Luxurious Sea-Lord", },
    {name:"Akuoumaru", },
    {name:"Dragon's Bane", },
    {name:"Prototype Starglitter", },
    {name:"Crescent Pike", },
    {name:"Blackcliff Pole", },
    {name:"Deathmatch", },
    {name:"Favonius Lance", },
    {name:"Royal Spear", },
    {name:"Dragonspine Spear", },
    {name:"Lithic Spear", },
    {name:"Kitain Cross Spear", },
    {name:"The Catch", },
    {name:"Wavebreaker's Fin", },
    {name:"Favonius Codex", },
    {name:"The Windsith", },
    {name:"Sacrificial Fragments", },
    {name:"Royal Grimoire", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },
    {name:"Dark Iron Sword", },



]);