//USED for Adding Data/ Backup Data
//load("C:Users/user/Documents/MiniProjects/MongoDBTestAPI/insertMany.js"); insertMany.js
db.Characters.insertMany([
    {name:"Amber",      star:4, element:"Pyro", type:"Bow" ,    region:"Mondstadt", domain:"Forsaken Rift", material:"Freedom", availability:["Sunday","Monday","Thursday"],        imgurl:"../../assets/data/images/characters/amber.png" },
    {name:"Kaeya",      star:4, element:"Cryo", type:"Sword" ,  region:"Mondstadt", domain:"Forsaken Rift", material:"Ballad",  availability:["Sunday","Wednesday","Saturday"],     imgurl:"../../assets/data/images/characters/amber.png" },
    {name:"Lisa"},
    {name:"Barbara"},
    {name:"Razor"},
    {name:"Xiangling"},
    {name:"Beidou"},
    {name:"Xingqiu"},
    {name:"Ningguang"},
    {name:"Fischl"},
    {name:"Bennett"},
    {name:"Noelle"},
    {name:"Chongyun"},
    {name:"Sucrose"},
    {name:"Jean"},
    {name:"Diluc"},
    {name:"Qiqi"},
    {name:"Mona"},
    {name:"Keqing"},
    {name:"Venti"},
    {name:"Klee"},
    {name:"Diona"},
    {name:"Tartaglia"},
    {name:"Xinyan"},
    {name:"Zhongli"},
    {name:"Albedo"},
    {name:"Ganyu"},
    {name:"Xiao"},
    {name:"Hu Tao"},
    {name:"Rosaria"},
    {name:"Yanfei"},
    {name:"Eula"},
    {name:"Kaedahara Kazuha"},
    {name:"Kamisato Ayaka"},
    {name:"Sayu"},
    {name:"Yoimiya"},
    {name:"Aloy"},
    {name:"Kujou Sara"},
    {name:"Raiden Shogun"},
    {name:"Sangonomiya Kokomi"},
    {name:"Thoma"},
    {name:"Gorou"}  ,
    {name:"Arataki Itto"},
    {name:"Yun Jin"},
    {name:"Shenhe"},
    {name:"Yae Miko"},
    {name:"Kamisato Ayato"},
    {name:"Kuki Shinobu"},
    {name:"Yelan"},
    {name:"Shikanoin Heizou"}

]);