//USED for Adding Data/ Backup Data or reference
//load("Documents/MiniProjects/MongoDBTestAPI/insertManyWeapons.js");

db.Weapons.insertMany([
    {name:"Dark Iron Sword",                    star:3, stat:"Elemental Mastery",     type:"Sword", domain:"Hidden Palace of Lianshan Formula",     material:"Guyun",     availability:["Sunday","Monday","Thursday"],        imgurl:"../../assets/data/images/weapons/BlackIronSword.png" },
    {name:"Cool Steel",                         star:3, stat:'ATK',                   },
    {name:"Harbinger of Dawn",                  star:3, stat:'CRIT DMG',              },
    {name:"Traveler's HAndy Sword",             star:3, stat:'DEF',                   },
    {name:"Fillet Blade",                       star:3, stat:'ATK',                   },
    {name:"Skyrider Sword",                     star:3, stat:'Energy Recharge',       },
    {name:"Ferrous Shadow",                     star:3, stat:'HP',                    },
    {name:"Bloodstained Greatsword",            star:3, stat:"Elemental Mastery",     },
    {name:"White Iron Greatsword",              star:3, stat:'DEF',                   },
    {name:"Debate Club",                        star:3, stat:'ATK',                   },
    {name:"Skyrider Greatsword",                star:3, stat:'Physical DMG Bonus',    },
    {name:"White Tassel",                       star:3, stat:'CRIT Rate',             },
    {name:"Halberd",                            star:3, stat:'ATK',                   },
    {name:"Black Tassel",                       star:3, stat:'HP',                    },
    {name:"Amber Bead",                         star:3, stat:"Elemental Mastery",     },
    {name:"Magic Guide",                        star:3, stat:"Elemental Mastery",     },
    {name:"Thrilling Tales of Dragon Slayers",  star:3, stat:'HP',                    },
    {name:"Otherwordly Story",                  star:3, stat:'Energy Recharge',       },
    {name:"Emerald Orb",                        star:3, stat:"Elemental Mastery",     },
    {name:"Twin Nepherite",                     star:3, stat:'CRIT Rate',             },
    {name:"Ebony Bow",                          star:3, stat:'ATK',                   },
    {name:"Raven Bow",                          star:3, stat:"Elemental Mastery",     },
    {name:"Sharpshooter's Oath",                star:3, stat:'CRIT DMG',              },
    {name:"Recurve Bow",                        star:3, stat:'HP',                    },
    {name:"Slingshot",                          star:3, stat:'CRIT Rate',             },
    {name:"Messenger",                          star:3, stat:'CRIT DMG',              },
    {name:"Favonius Sword",                     star:4, stat:'Energy Recharge',       },
    {name:"The Flute",                          star:4, stat:'ATK',                   },
    {name:"Sacrificial Sword",                  star:4, stat:'Energy Recharge',       },
    {name:"Royal Longsword",                    star:4, stat:'ATK',                   },
    {name:"Lion's Roar",                        star:4, stat:'ATK',                   },
    {name:"Prototype Rancour",                  star:4, stat:'Physical DMG Bonus',    },
    {name:"Iron Sting",                         star:4, stat:"Elemental Mastery",     },
    {name:"Blackcliff Longsword",               star:4, stat:'CRIT DMG',              },
    {name:"Sword of Descension",                star:4, stat:'ATK',                   },
    {name:"Festering Desire",                   star:4, stat:'Energy Recharge',       },
    {name:"The Alley Flash",                    star:4, stat:"Elemental Mastery",     },
    {name:"Amenoma Kageuchi",                   star:4, stat:'ATK',                   },
    {name:"Cinnabar Spindle",                   star:4, stat:'DEF',                   },
    {name:"Favonius Greatsword",                star:4, stat:'Energy Recharge',       },
    {name:"The Bell",                           star:4, stat:'HP',                    },
    {name:"Sacrificial Greatsword",             star:4, stat:'Energy Recharge',       },
    {name:"Royal Greatsword",                   star:4, stat:'ATK',                   },
    {name:"Rainslasher",                        star:4, stat:"Elemental Mastery",     },
    {name:"Prototype Archaic",                  star:4, stat:'ATK',                   },
    {name:"Whiteblind",                         star:4, stat:'DEF',                   },
    {name:"Blackcliff Slasher",                 star:4, stat:'CRIT DMG',              },
    {name:"Serpent Spine",                      star:4, stat:'CRIT Rate',             },
    {name:"Snow-Tombed Starsilver",             star:4, stat:'Physical DMG Bonus',    },
    {name:"Lithic Blade",                       star:4, stat:'ATK',                   },
    {name:"Katsuragikiri Nagamasa",             star:4, stat:'Energy Recharge',       },
    {name:"Luxurious Sea-Lord",                 star:4, stat:'ATK',                   },
    {name:"Akuoumaru",                          star:4, stat:'ATK',                   },
    {name:"Dragon's Bane",                      star:4, stat:"Elemental Mastery",     },
    {name:"Prototype Starglitter",              star:4, stat:'Energy Recharge',       },
    {name:"Crescent Pike",                      star:4, stat:'Physical DMG Bonus',    },
    {name:"Blackcliff Pole",                    star:4, stat:'CRIT DMG',              },
    {name:"Deathmatch",                         star:4, stat:'CRIT Rate',             },
    {name:"Favonius Lance",                     star:4, stat:'Energy Recharge',       },
    {name:"Royal Spear",                        star:4, stat:'ATK',                   },
    {name:"Dragonspine Spear",                  star:4, stat:'Physical DMG Bonus',    },
    {name:"Lithic Spear",                       star:4, stat:'ATK',                   },
    {name:"Kitain Cross Spear",                 star:4, stat:"Elemental Mastery",     },
    {name:"The Catch",                          star:4, stat:'Energy Recharge',       },
    {name:"Wavebreaker's Fin",                  star:4, stat:'ATK',                   },
    {name:"Favonius Codex",                     star:4, stat:'Energy Recharge',       },
    {name:"The Windsith",                       star:4, stat:'CRIT DMG',              },
    {name:"Sacrificial Fragments",              star:4, stat:'Energy Recharge',       },
    {name:"Royal Grimoire",                     star:4, stat:'ATK',                   },
    {name:"Solar Pearl",                        star:4, stat:'CRIT Rate',             },
    {name:"Prototype Amber",                    star:4, stat:'HP',                    },
    {name:"Mappa Mare",                         star:4, stat:"Elemental Mastery",     },
    {name:"Blackcliff Agate",                   star:4, stat:'CRIT DMG',              },
    {name:"Eye of Perception",                  star:4, stat:'ATK',                   },
    {name:"Frostbearer",                        star:4, stat:'ATK',                   },
    {name:"Dodoco Tales",                       star:4, stat:'ATK',                   },
    {name:"Wine and Song",                      star:4, stat:'Energy Recharge',       },
    {name:"Hakushin Ring",                      star:4, stat:'Energy Recharge',       },
    {name:"Oathsworn Eye",                      star:4, stat:'ATK',                   },
    {name:"Favonius Warbow",                    star:4, stat:'Energy Recharge',       },
    {name:"The Stringless",                     star:4, stat:"Elemental Mastery",     },
    {name:"Sacrificial Bow",                    star:4, stat:'Energy Recharge',       },
    {name:"Royal Bow",                          star:4, stat:'ATK',                   },
    {name:"Rust",                               star:4, stat:'ATK',                   },
    {name:"Prototype Crescent",                 star:4, stat:'ATK',                   },
    {name:"Compound Bow",                       star:4, stat:'Physical DMG Bonus',    },
    {name:"Blackcliff Warbow",                  star:4, stat:'CRIT DMG',              },
    {name:"The Viridescent Hunt",               star:4, stat:'CRIT Rate',             },
    {name:"Windblume Ode",                      star:4, stat:"Elemental Mastery",     },
    {name:"Alley Hunter",                       star:4, stat:'ATK',                   },
    {name:"Mitternachts Waltz",                 star:4, stat:'Physical DMG Bonus',    },
    {name:"Hamayumi",                           star:4, stat:'ATK',                   },
    {name:"Predator",                           star:4, stat:'ATK',                   },
    {name:"Mouun's Moon",                       star:4, stat:'ATK',                   },
    {name:"Fading Twilight",                    star:4, stat:'Energy Recharge',       },
    {name:"Aquila Favonia",                     star:5, stat:'Physical DMG Bonus',    },
    {name:"Skyward Blade",                      star:5, stat:'Energy Recharge',       },
    {name:"Summit Shaper",                      star:5, stat:'ATK',                   },
    {name:"Primordial Jade Cutter",             star:5, stat:'CRIT Rate',             },
    {name:"Freedom-Sworn",                      star:5, stat:"Elemental Mastery",     },
    {name:"Mistsplitter Reforged",              star:5, stat:'CRIT DMG',              },
    {name:"Haran Geppaku Futsu",                star:5, stat:'CRIT Rate',             },
    {name:"Skyward Pride",                      star:5, stat:'Energy Recharge',       },
    {name:"The Unforged",                       star:5, stat:'ATK',                   },
    {name:"Song of Broken Pines",               star:5, stat:'Physical DMG Bonus',    },
    {name:"Redhorn Stonethresher",              star:5, stat:'CRIT DMG',              },
    {name:"Vortex Vanguisher",                  star:5, stat:'ATK',                   },
    {name:"Primordial Jade Winged-Spear",       star:5, stat:'CRIT Rate',             },
    {name:"Skyward Spine",                      star:5, stat:'Energy Recharge',       },
    {name:"Staff of Homa",                      star:5, stat:'CRIT DMG',              },
    {name:"Engulfing Lighting",                 star:5, stat:'Energy Recharge',       },
    {name:"Calamity Queller",                   star:5, stat:'ATK',                   },
    {name:"Lost Prayer to the Sacred Winds",    star:5, stat:'CRIT Rate',             },
    {name:"Skyward Atlas",                      star:5, stat:'ATK',                   },
    {name:"Memory of Dust",                     star:5, stat:'ATK',                   },
    {name:"Everlasting Moonglow",               star:5, stat:'HP',                    },
    {name:"Kagura's Verity",                    star:5, stat:'CRIT DMG',              },
    {name:"Skyward Harp",                       star:5, stat:'CRIT Rate',             },
    {name:"Amo's Bow",                          star:5, stat:'ATK',                   },
    {name:"Elegy For The End",                  star:5, stat:'Energy Recharge',       },
    {name:"Thundering Pulse",                   star:5, stat:'CRIT DMG',              },
    {name:"Polar Star",                         star:5, stat:'CRIT Rate',             },
    {name:"Aqua Simulacra",                     star:5, stat:'CRIT DMG',              },
]);