-- 

INSERT INTO  Weapons (Name,Star, WeaponType_ID, SecondStat_ID, Domain_ID, DomainMaterial_ID, Availabilities, ImgURL) 
VALUES
--Name                                 Str  Wt 2nsSt
--3 Stars
('Dark Iron Sword',                      3, 1, 6),
('Cool Steel',                           3, 1, 1),
('Harbinger of Dawm',                    3, 1, 7),
('Traveler''s Handy Sword',              3, 1, 3),
('Fillet Blade',                         3, 1, 1),
('Skyrider Sword',                       3, 1, 5),
('Ferrous Shadow',                       3, 2),
('Bloodstained GreatSword',              3, 2),
('White Iron Greatsword',                3, 2),
('Debate Club',                          3, 2),
('Skyrider Greatsword',                  3, 2),
('White Tassel',                         3, 3),
('Halberd',                              3, 3),
('Black Tassel',                         3, 3),
('Magic Guide',                          3, 4),
('Thrilling Tales of Dragon Slayers',    3, 4),
('Otherwordly Story',                    3, 4),                 
('Emerald Orb',                          3, 4),
('Twin Nepherite',                       3, 4),
('Ebony Bow',                            3, 5),
('Raven Bow',                            3, 5),
('Sharpshooter''s Oath',                 3, 5),
('Recurve Bow',                          3, 5),
('Slingshot',                            3, 5),
('Messenger',                            3, 5),
--4 Stars
('Favonius Sword',                       4, 1, 5),
('The Flute',                            4, 1, 1),
('Sacrificial Sword',                    4, 1, 5),
('Royal Longsword',                      4, 1, 1),
('Lion''s Roar',                         4, 1, 1),
('Prototype Rancour',                    4, 1, 4),
('Iron Sting',                           4, 1, 6),
('Blackcliff Longsword',                 4, 1, 7),
('The Black Sword',                      4, 1, 8),
('Sword of Descension',                  4, 1, 1),
('Festering Desire',                     4, 1, 5),
('The Alley Flash',                      4, 1, 6),
('Amenoma Kageuchi',                     4, 1, 1),
('Cinnabar Spindle',                     4, 1, 3),
('Favonious Greatsword',                 4, 2),
('The Bell',                             4, 2),
('Sacrifical Greatsword',                4, 2),
('Royal Greatsword',                     4, 2),
('Rainslasher',                          4, 2),
('Prototype Archaic',                    4, 2),
('Whiteblind',                           4, 2),
('Blackcliff Slasher',                   4, 2),
('Serpent Spine',                        4, 2),
('Snow-Tombed Starsilver',               4, 2),
('Lithic Blade',                         4, 2),
('Katsuragikiri Nagamasa',               4, 2),
('Luxurious Sea-Lord',                   4, 2),
('Akuoumaru',                            4, 2),
('Dragon''s Bane',                       4, 3),
('Prototype Starglitter',                4, 3),
('Crescent Pike',                        4, 3),
('Blackcliff Pole',                      4, 3),
('Deathmatch',                           4, 3),
('Favonius Lance',                       4, 3),
('Royal Spear',                          4, 3),
('Dragonspine Spear',                    4, 3),
('Lithic Spear',                         4, 3),
('Kitain Cross Spear',                   4, 3),
('The Catch',                            4, 3),
('Wavebreaker''s Fin',                   4, 3),
('Favonius Codex',                       4, 4),
('The Wisdith',                          4, 4),
('Sacrificial Fragments',                4, 4),
('Royal Grimoire',                       4, 4),
('Solar Pearl',                          4, 4),
('Prototype Amber',                      4, 4),
('Mappa Mare',                           4, 4),
('Blackcliff Agate',                     4, 4),
('Eye of Perception',                    4, 4),
('Frostbearer',                          4, 4),
('Wine and Song',                        4, 4),
('Hakushin Ring',                        4, 4),
('Oathsworn Eye',                        4, 4),
('Favonius Warbow',                      4, 5),
('The Stringless',                       4, 5),
('Sacrificial Bow',                      4, 5),
('Royal Bow',                            4, 5),
('Rust',                                 4, 5),
('Prototype Cresecent',                  4, 5),
('Compound Bow',                         4, 5),
('Blackcliff Warbow',                    4, 5),
('The Viridescent Hunt',                 4, 5),
('Windblume Ode',                        4, 5),
('Alley Hunter',                         4, 5),
('Mitternachts Waltz',                   4, 5),
('Hamayumi',                             4, 5),
('Mouun''s Moon',                        4, 5),
('Fading Twilight',                      4, 5),
--5 Star
('Aquila Favonia',                       5, 1, 4),
('Skyward Blade',                        5, 1, 5),
('Summit Shaper',                        5, 1, 1),
('Primordial Jade Cutter',               5, 1, 8),
('Freedom-Sword',                        5, 1, 6),
('Mistsplitter Reforged',                5, 1, 7),
('Haran Geppaku Futsu',                  5, 1),
('Skyward Pride',                        5, 2),
('Wolf''s Gravestone',                   5, 2),
('The Unforged',                         5, 2),
('Song of Broken Pines',                 5, 2),
('Redhorn Stonethresher',                5, 2),
('Vortex Vanguisher',                    5, 3),
('Primordial Jade Winged-Spear',         5, 3),
('Skyward Spine',                        5, 3),
('Staff of Homa',                        5, 3),
('Engulfing Lighting',                   5, 3),
('Calamity Queller',                     5, 3),
('Lost Prayer to the Sacred Winds',      5, 4),
('Skyward Atlas',                        5, 4),
('Memory of Dust',                       5, 4),
('Everlasting Moonglow',                 5, 4),
('Kagura''s Verity',                     5, 4),
('Skyward Harp',                         5, 5),
('Amo''s Bow',                           5, 5),
('Elegy of the End',                     5, 5),
('Thundering Pulse',                     5, 5),
('Polar Star',                           5, 5),
('Aqua Simulacra ',                      5, 5)