--Credits to (https://genshin.honeyhunterworld.com/) for the Data
INSERT INTO  Weapons (Name,Star, WeaponType_ID, SecondStat_ID, Domain_ID, DomainMaterial_ID, Availabilties, ImgURL) 
VALUES
--Name                                 Str  Wt 2S D  Dm A  urlIN
--3 Stars
('Dark Iron Sword',                      3, 1, 6, 4, 4, 1, '../../assets/data/images/weapons/BlackIronSword.png'),
('Cool Steel',                           3, 1, 1, 2, 1, 1, '../../assets/data/images/weapons/CoolSteel.png'),
('Harbinger of Dawn',                    3, 1, 7, 2, 2, 2, '../../assets/data/images/weapons/HarbingerOfDawn.png'),
('Traveler''s Handy Sword',              3, 1, 3, 2, 3, 3, '../../assets/data/images/weapons/TravelersHandySword.png'),
('Fillet Blade',                         3, 1, 1, 4, 5, 2, '../../assets/data/images/weapons/FilletBlade.png'),
('Skyrider Sword',                       3, 1, 5, 4, 6, 3, '../../assets/data/images/weapons/SkyriderSword.png'),
('Ferrous Shadow',                       3, 2, 2, 2, 1, 1, '../../assets/data/images/weapons/FerrousShadow.png'),
('Bloodstained Greatsword',              3, 2, 6, 2, 2, 2, '../../assets/data/images/weapons/BloodtaintedGreatsword.png'),
('White Iron Greatsword',                3, 2, 3, 2, 3, 3, '../../assets/data/images/weapons/WhiteIronGreatsword.png'),
('Debate Club',                          3, 2, 1, 4, 5, 2, '../../assets/data/images/weapons/DebateClub.png'),
('Skyrider Greatsword',                  3, 2, 4, 4, 6, 3, '../../assets/data/images/weapons/SkyriderGreatsword.png'),
('White Tassel',                         3, 3, 8, 4, 4, 1, '../../assets/data/images/weapons/WhiteTassel.png'),
('Halberd',                              3, 3, 1, 2, 5, 2, '../../assets/data/images/weapons/Halberd.png'),
('Black Tassel',                         3, 3, 2, 4, 6, 3, '../../assets/data/images/weapons/BlackTassel.png'),
('Amber Bead',                           3, 4, 6, 4, 6, 3, '../../assets/data/images/weapons/AmberBead.png'),
('Magic Guide',                          3, 4, 6, 2, 1, 1, '../../assets/data/images/weapons/MagicGuide.png'),
('Thrilling Tales of Dragon Slayers',    3, 4, 2, 2, 2, 2, '../../assets/data/images/weapons/ThrillingTalesOfDragonSlayers.png'),
('Otherwordly Story',                    3, 4, 5, 2, 3, 3, '../../assets/data/images/weapons/OtherworldlyStory.png'),                 
('Emerald Orb',                          3, 4, 6, 4, 4, 1, '../../assets/data/images/weapons/EmeraldOrb.png'),
('Twin Nepherite',                       3, 4, 8, 4, 5, 2, '../../assets/data/images/weapons/TwinNephrite.png'),
('Ebony Bow',                            3, 5, 1, 4, 6, 3, '../../assets/data/images/weapons/EbonyBow.png'),
('Raven Bow',                            3, 5, 6, 2, 1, 1, '../../assets/data/images/weapons/RavenBow.png'),
('Sharpshooter''s Oath',                 3, 5, 7, 2, 2, 2, '../../assets/data/images/weapons/SharpshootersOath.png'),
('Recurve Bow',                          3, 5, 2, 2, 3, 3, '../../assets/data/images/weapons/RecurveBow.png'),
('Slingshot',                            3, 5, 8, 4, 4, 1, '../../assets/data/images/weapons/Slingshot.png'),
('Messenger',                            3, 5, 7, 4, 5, 2, '../../assets/data/images/weapons/Messenger.png'),
--4 Stars
('Favonius Sword',                       4, 1, 5, 2, 1, 1, '../../assets/data/images/weapons/FavoniusSword.png'),
('The Flute',                            4, 1, 1, 2, 2, 2, '../../assets/data/images/weapons/TheFlute.png'),
('Sacrificial Sword',                    4, 1, 5, 2, 3, 3, '../../assets/data/images/weapons/SacrificialSword.png'),
('Royal Longsword',                      4, 1, 1, 2, 1, 1, '../../assets/data/images/weapons/RoyalLongsword.png'),
('Lion''s Roar',                         4, 1, 1, 4, 4, 1, '../../assets/data/images/weapons/LionsRoar.png'),
('Prototype Rancour',                    4, 1, 4, 4, 5, 2, '../../assets/data/images/weapons/PrototypeRancour.png'),
('Iron Sting',                           4, 1, 6, 4, 6, 3, '../../assets/data/images/weapons/IronSting.png'),
('Blackcliff Longsword',                 4, 1, 7, 4, 4, 1, '../../assets/data/images/weapons/BlackcliffLongsword.png'),
('The Black Sword',                      4, 1, 8, 2, 2, 2, '../../assets/data/images/weapons/TheBlackSword.png'),
('Sword of Descension',                  4, 1, 1, 2, 2, 2, '../../assets/data/images/weapons/SwordOfDescension.png'),
('Festering Desire',                     4, 1, 5, 2, 3, 3, '../../assets/data/images/weapons/Festering Desire.png'),
('The Alley Flash',                      4, 1, 6, 2, 1, 1, '../../assets/data/images/weapons/TheAlleyFlash.png'),
('Amenoma Kageuchi',                     4, 1, 1, 6, 7, 1, '../../assets/data/images/weapons/AmenomaKageuchi.png'),
('Cinnabar Spindle',                     4, 1, 3, 2, 1, 1, '../../assets/data/images/weapons/CinnabarSpindle.png'),
('Favonious Greatsword',                 4, 2, 5, 2, 3, 3, '../../assets/data/images/weapons/FavoniousGreatsword.png'),
('The Bell',                             4, 2, 2, 2, 1, 1, '../../assets/data/images/weapons/TheBell.png'),
('Sacrifical Greatsword',                4, 2, 5, 2, 2, 2, '../../assets/data/images/weapons/SacrificialGreatsword.png'),
('Royal Greatsword',                     4, 2, 1, 2, 3, 3, '../../assets/data/images/weapons/RoyalGreatsword.png'),
('Rainslasher',                          4, 2, 6, 4, 5, 2, '../../assets/data/images/weapons/Rainslasher.png'),
('Prototype Archaic',                    4, 2, 1, 4, 6, 3, '../../assets/data/images/weapons/PrototypeArchaic.png'),
('Whiteblind',                           4, 2, 3, 4, 4, 1, '../../assets/data/images/weapons/Whiteblind.png'),
('Blackcliff Slasher',                   4, 2, 7, 4, 5, 2, '../../assets/data/images/weapons/BlackcliffSlasher.png'),
('Serpent Spine',                        4, 2, 8, 4, 6, 3, '../../assets/data/images/weapons/SerpentSpine.png'),
('Snow-Tombed Starsilver',               4, 2, 4, 2, 1, 1, '../../assets/data/images/weapons/Snow-TombedStarsilver.png'),
('Lithic Blade',                         4, 2, 1, 4, 4, 1, '../../assets/data/images/weapons/LithicBlade.png'),
('Katsuragikiri Nagamasa',               4, 2, 5, 6, 8, 2, '../../assets/data/images/weapons/KatsuragikiriNagamasa.png'),
('Luxurious Sea-Lord',                   4, 2, 1, 4, 6, 3, '../../assets/data/images/weapons/LuxuriousSea-Lord.png'),
('Akuoumaru',                            4, 2, 1, 6, 7, 1, '../../assets/data/images/weapons/Akuoumaru.png'),
('Dragon''s Bane',                       4, 3, 6, 4, 5, 2, '../../assets/data/images/weapons/DragonsBane.png'),
('Prototype Starglitter',                4, 3, 5, 4, 6, 3, '../../assets/data/images/weapons/PrototypeStarglitter.png'),
('Crescent Pike',                        4, 3, 4, 4, 4, 1, '../../assets/data/images/weapons/CrescentPike.png'),
('Blackcliff Pole',                      4, 3, 7, 4, 5, 2, '../../assets/data/images/weapons/BlackcliffPole.png'),
('Deathmatch',                           4, 3, 8, 2, 2, 2, '../../assets/data/images/weapons/Deathmatch.png'),
('Favonius Lance',                       4, 3, 5, 2, 3, 3, '../../assets/data/images/weapons/FavoniusLance.png'),
('Royal Spear',                          4, 3, 1, 2, 5, 2, '../../assets/data/images/weapons/RoyalSpear.png'),
('Dragonspine Spear',                    4, 3, 4, 2, 2, 2, '../../assets/data/images/weapons/DragonspineSpear.png'),
('Lithic Spear',                         4, 3, 1, 4, 6, 3, '../../assets/data/images/weapons/LithicSpear.png'),
('Kitain Cross Spear',                   4, 3, 6, 6, 9, 3, '../../assets/data/images/weapons/KitainCrossSpear.png'),
('The Catch',                            4, 3, 5, 6, 9, 3, '../../assets/data/images/weapons/TheCatch.png'),
('Wavebreaker''s Fin',                   4, 3, 1, 6, 9, 3, '../../assets/data/images/weapons/WavebreakersFin.png'),
('Favonius Codex',                       4, 4, 5, 2, 1, 1, '../../assets/data/images/weapons/FavoniusCodex.png'),
('The Wisdith',                          4, 4, 7, 2, 2, 2, '../../assets/data/images/weapons/TheWidsith.png'),
('Sacrificial Fragments',                4, 4, 5, 2, 3, 3, '../../assets/data/images/weapons/SacrificialFragments.png'),
('Royal Grimoire',                       4, 4, 1, 2, 1, 1, '../../assets/data/images/weapons/RoyalGrimoire.png'),
('Solar Pearl',                          4, 4, 8, 4, 4, 1, '../../assets/data/images/weapons/SolarPearl.png'),
('Prototype Amber',                      4, 4, 2, 4, 5, 2, '../../assets/data/images/weapons/PrototypeAmber.png'),
('Mappa Mare',                           4, 4, 6, 4, 6, 3, '../../assets/data/images/weapons/MappaMare.png'),
('Blackcliff Agate',                     4, 4, 7, 4, 4, 1, '../../assets/data/images/weapons/BlackcliffAgate.png'),
('Eye of Perception',                    4, 4, 1, 4, 5, 2, '../../assets/data/images/weapons/EyeOfPerception.png'),
('Frostbearer',                          4, 4, 1, 2, 3, 3, '../../assets/data/images/weapons/Frostbearer.png'),
('Dodoco Tales',                         4, 4, 1, 2, 2, 2, '../../assets/data/images/weapons/DodocoTales.png'),
('Wine and Song',                        4, 4, 5, 2, 2, 2, '../../assets/data/images/weapons/WineAndSong.png'),
('Hakushin Ring',                        4, 4, 5, 6, 7, 1, '../../assets/data/images/weapons/HakushinRing.png'),
('Oathsworn Eye',                        4, 4, 1, 6, 7, 1, '../../assets/data/images/weapons/OathswornEye.png'),
('Favonius Warbow',                      4, 5, 5, 2, 3, 3, '../../assets/data/images/weapons/FavoniusWarbow.png'),
('The Stringless',                       4, 5, 6, 2, 1, 1, '../../assets/data/images/weapons/TheStringless.png'),
('Sacrificial Bow',                      4, 5, 5, 2, 2, 2, '../../assets/data/images/weapons/SacrificialBow.png'),
('Royal Bow',                            4, 5, 1, 2, 3, 3, '../../assets/data/images/weapons/RoyalBow.png'),
('Rust',                                 4, 5, 1, 4, 4, 1, '../../assets/data/images/weapons/Rust.png'),
('Prototype Cresecent',                  4, 5, 1, 4, 5, 2, '../../assets/data/images/weapons/PrototypeCrescent.png'),
('Compound Bow',                         4, 5, 4, 4, 6, 3, '../../assets/data/images/weapons/CompoundBow.png'),
('Blackcliff Warbow',                    4, 5, 7, 4, 4, 1, '../../assets/data/images/weapons/BlackcliffWarbow.png'),
('The Viridescent Hunt',                 4, 5, 8, 2, 1, 1, '../../assets/data/images/weapons/TheViridescentHunt.png'),
('Windblume Ode',                        4, 5, 6, 2, 3, 3, '../../assets/data/images/weapons/WindblumeOde.png'),
('Alley Hunter',                         4, 5, 1, 2, 3, 3, '../../assets/data/images/weapons/AlleyHunter.png'),
('Mitternachts Waltz',                   4, 5, 4, 2, 1, 1, '../../assets/data/images/weapons/MitternachtsWaltz.png'),
('Hamayumi',                             4, 5, 1, 6, 8, 2, '../../assets/data/images/weapons/Hamayumi.png'),
('Predator',                             4, 5, 1, 6, 8, 2, '../../assets/data/images/weapons/Predator.png'),
('Mouun''s Moon',                        4, 5, 1, 6, 8, 2, '../../assets/data/images/weapons/MouunsMoon.png'),
('Fading Twilight',                      4, 5, 5, 4, 6, 3, '../../assets/data/images/weapons/FadingTwilight.png'),
--5 Star
('Aquila Favonia',                       5, 1, 4, 2, 1, 1, '../../assets/data/images/weapons/AquilaFavonia.png'),
('Skyward Blade',                        5, 1, 5, 2, 2, 2, '../../assets/data/images/weapons/SkywardBlade.png'),
('Summit Shaper',                        5, 1, 1, 4, 4, 1, '../../assets/data/images/weapons/SummitShaper.png'),
('Primordial Jade Cutter',               5, 1, 8, 4, 5, 2, '../../assets/data/images/weapons/PrimordialJadeCutter.png'),
('Freedom-Sworn',                        5, 1, 6, 2, 3, 3, '../../assets/data/images/weapons/Freedom-Sworn.png'),
('Mistsplitter Reforged',                5, 1, 7, 6, 7, 1, '../../assets/data/images/weapons/MistsplitterReforged.png'),
('Haran Geppaku Futsu',                  5, 1, 8, 6, 8, 2, '../../assets/data/images/weapons/HaranGeppakuFutsu.png'),
('Skyward Pride',                        5, 2, 5, 2, 2, 2, '../../assets/data/images/weapons/WolfsGravestone.png'),
('The Unforged',                         5, 2, 1, 4, 5, 2, '../../assets/data/images/weapons/TheUnforged.png'),
('Song of Broken Pines',                 5, 2, 4, 2, 1, 1, '../../assets/data/images/weapons/SongOfBrokenPines.png'),
('Redhorn Stonethresher',                5, 2, 7, 6, 8, 2, '../../assets/data/images/weapons/RedhornStonethresher.png'),
('Vortex Vanguisher',                    5, 3, 1, 4, 6, 3, '../../assets/data/images/weapons/VortexVanquisher.png'),
('Primordial Jade Winged-Spear',         5, 3, 8, 4, 4, 1, '../../assets/data/images/weapons/PrimordialJadeWinged-Spear.png'),
('Skyward Spine',                        5, 3, 5, 2, 3, 3, '../../assets/data/images/weapons/SkywardSpine.png'),
('Staff of Homa',                        5, 3, 7, 4, 6, 3, '../../assets/data/images/weapons/StaffOfHoma.png'),
('Engulfing Lighting',                   5, 3, 5, 6, 9, 3, '../../assets/data/images/weapons/EngulfingLightning.png'),
('Calamity Queller',                     5, 3, 1, 4, 5, 2, '../../assets/data/images/weapons/CalamityQueller.png'),
('Lost Prayer to the Sacred Winds',      5, 4, 8, 2, 3, 3, '../../assets/data/images/weapons/LostPrayerToTheSacredWinds.png'),
('Skyward Atlas',                        5, 4, 1, 3, 2, 2, '../../assets/data/images/weapons/SkywardAtlas.png'),
('Memory of Dust',                       5, 4, 1, 4, 6, 3, '../../assets/data/images/weapons/MemoryOfDust.png'),
('Everlasting Moonglow',                 5, 4, 2, 6, 7, 1, '../../assets/data/images/weapons/EverlastingMoonglow.png'),
('Kagura''s Verity',                     5, 4, 7, 6, 9, 3, '../../assets/data/images/weapons/KagurasVerity.png'),
('Skyward Harp',                         5, 5, 8, 2, 2, 2, '../../assets/data/images/weapons/SkywardHarp.png'),
('Amo''s Bow',                           5, 5, 1, 2, 3, 3, '../../assets/data/images/weapons/AmosBow.png'),
('Elegy For The End',                    5, 5, 5, 2, 2, 2, '../../assets/data/images/weapons/ElegyForTheEnd.png'),
('Thundering Pulse',                     5, 5, 7, 6, 8, 2, '../../assets/data/images/weapons/ThunderingPulse.png'),
('Polar Star',                           5, 5, 8, 6, 9, 3, '../../assets/data/images/weapons/PolarStar.png'),
('Aqua Simulacra ',                      5, 5, 7, 4, 4, 1, '../../assets/data/images/weapons/AquaSimulacra.png')
;